### ISSUE TITLE
False Positive issue

### ISSUE THREAD

**Issue by CaptainBasculin** [andmydignity/anti-tayyip-bot#2]
Currently, the bot takes any post that includes string 'rte', this causes a lot of false positives. One example can be seen [here](https://www.reddit.com/r/Turkey/comments/wz5yb8/-/im0iqcs):

Since there exists words that include the string "rte", it's likely for it to get false positived.

I would reccomend to fix it with a logic like this:

if the string "rte" is the one being parsed, check for spaces in front of it/behind it, or whether it's located right at the end/beginning of the parsed text. If two of these apply, comment. Else, ignore

**Comment by andmydignity** [comment]
thanks for informing,but i don't think i will fixing it since i see it as 'just a little goofy bot'

**Comment by andmydignity** [comment]
Ok decided to fix it now with a 'lazy' solution
